contacts:
  photo:
    storage: etc/photos
    resize-width: 150
    resize-height: 150

security:
  user:
    name: admin
    password: admin123
  basic:
    realm: Please provide your authentication details

management:
  #port: 8081
  address: 127.0.0.1
  context-path: /manage
  security:
    enabled: true
    role: SUPERUSER
  
shell:
  ssh:
    enabled: true
    port: 2222
  auth: spring
